services:
  postgres:
    image: postgres:alpine
    container_name: postgress-nest
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - '5432:5432'